//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from f:\VisualProjects\Text2Scratch\Text2Scratch\Text2Object\T2S.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="T2SParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IT2SListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="T2SParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] T2SParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="T2SParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] T2SParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="T2SParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] T2SParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="T2SParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] T2SParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="T2SParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] T2SParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="T2SParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] T2SParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="T2SParser.ifBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfBlock([NotNull] T2SParser.IfBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="T2SParser.ifBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfBlock([NotNull] T2SParser.IfBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="T2SParser.elseIfBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseIfBlock([NotNull] T2SParser.ElseIfBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="T2SParser.elseIfBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseIfBlock([NotNull] T2SParser.ElseIfBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="T2SParser.whileBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileBlock([NotNull] T2SParser.WhileBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="T2SParser.whileBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileBlock([NotNull] T2SParser.WhileBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="T2SParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] T2SParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="T2SParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] T2SParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="T2SParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] T2SParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="T2SParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] T2SParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>comparasionExpression</c>
	/// labeled alternative in <see cref="T2SParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparasionExpression([NotNull] T2SParser.ComparasionExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>comparasionExpression</c>
	/// labeled alternative in <see cref="T2SParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparasionExpression([NotNull] T2SParser.ComparasionExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>parenthesizedExpression</c>
	/// labeled alternative in <see cref="T2SParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthesizedExpression([NotNull] T2SParser.ParenthesizedExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>parenthesizedExpression</c>
	/// labeled alternative in <see cref="T2SParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthesizedExpression([NotNull] T2SParser.ParenthesizedExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>constantExpression</c>
	/// labeled alternative in <see cref="T2SParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstantExpression([NotNull] T2SParser.ConstantExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>constantExpression</c>
	/// labeled alternative in <see cref="T2SParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstantExpression([NotNull] T2SParser.ConstantExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>additiveExpression</c>
	/// labeled alternative in <see cref="T2SParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpression([NotNull] T2SParser.AdditiveExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>additiveExpression</c>
	/// labeled alternative in <see cref="T2SParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpression([NotNull] T2SParser.AdditiveExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>identifierExpression</c>
	/// labeled alternative in <see cref="T2SParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierExpression([NotNull] T2SParser.IdentifierExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>identifierExpression</c>
	/// labeled alternative in <see cref="T2SParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierExpression([NotNull] T2SParser.IdentifierExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>functionCallExpression</c>
	/// labeled alternative in <see cref="T2SParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCallExpression([NotNull] T2SParser.FunctionCallExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>functionCallExpression</c>
	/// labeled alternative in <see cref="T2SParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCallExpression([NotNull] T2SParser.FunctionCallExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>notExpression</c>
	/// labeled alternative in <see cref="T2SParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotExpression([NotNull] T2SParser.NotExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>notExpression</c>
	/// labeled alternative in <see cref="T2SParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotExpression([NotNull] T2SParser.NotExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>multiplicativeExpression</c>
	/// labeled alternative in <see cref="T2SParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpression([NotNull] T2SParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>multiplicativeExpression</c>
	/// labeled alternative in <see cref="T2SParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpression([NotNull] T2SParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>booleanExpression</c>
	/// labeled alternative in <see cref="T2SParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBooleanExpression([NotNull] T2SParser.BooleanExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>booleanExpression</c>
	/// labeled alternative in <see cref="T2SParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBooleanExpression([NotNull] T2SParser.BooleanExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="T2SParser.multOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultOp([NotNull] T2SParser.MultOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="T2SParser.multOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultOp([NotNull] T2SParser.MultOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="T2SParser.addOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddOp([NotNull] T2SParser.AddOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="T2SParser.addOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddOp([NotNull] T2SParser.AddOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="T2SParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompareOp([NotNull] T2SParser.CompareOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="T2SParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompareOp([NotNull] T2SParser.CompareOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="T2SParser.boolOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolOp([NotNull] T2SParser.BoolOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="T2SParser.boolOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolOp([NotNull] T2SParser.BoolOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="T2SParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] T2SParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="T2SParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] T2SParser.ConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="T2SParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] T2SParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="T2SParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] T2SParser.BlockContext context);
}
