namespace Text2Scratch.ScratchObjects
{
    public enum ScratchBlockOpCode
    {
        //Control primitives
        control_repeat, control_repeat_until, control_while, control_for_each, control_forever,
        control_wait, control_wait_until, control_if, control_if_else, control_stop,
        control_create_clone_of, control_delete_this_clone,
        control_get_counter, control_incr_counter, control_clear_counter, control_all_at_once,
        //Control hats
        control_start_as_clone,
        //Control menus
        control_create_clone_of_menu,
        //Data primitives
        data_variable, data_setvariableto, data_changevariableby, data_hidevariable, data_showvariable,
        data_listcontents, data_addtolist, data_deleteoflist, data_deletealloflist, data_insertatlist,
        data_replaceitemoflist, data_itemoflist, data_itemnumoflist, data_lengthoflist, data_listcontainsitem,
        data_hidelist, data_showlist,
        //Event primitives
        event_broadcast, event_broadcastandwait,
        //Event hats
        event_whenflagclicked, event_whenkeypressed, event_whenthisspriteclicked, event_whentouchingobject,
        event_whenstageclicked, event_whenbackdropswitchesto, event_whengreaterthan, event_whenbroadcastreceived,
        //Look primitives
        looks_say, looks_sayforsecs, looks_think, looks_thinkforsecs, looks_show, looks_hide, looks_hideallsprites,
        looks_switchcostumeto, looks_switchbackdropto, looks_switchbackdroptoandwait,
        looks_nextcostume, looks_nextbackdrop, looks_changeeffectby, looks_seteffectto, looks_cleargraphiceffects,
        looks_changesizeby, looks_setsizeto, looks_changestretchby, looks_setstretchto,
        looks_gotofrontback, looks_goforwardbackwardlayers,
        looks_size, looks_costumenumbername, looks_backdropnumbername,
        //Look menus
        looks_costume, looks_backdrops,
        //Motion primitives
        motion_movesteps, motion_gotoxy, motion_goto, motion_turnright, motion_turnleft,
        motion_pointindirection, motion_pointtowards, motion_glidesecstoxy, motion_glideto,
        motion_ifonedgebounce, motion_setrotationstyle,
        motion_changexby, motion_setx, motion_changeyby,
        motion_sety, motion_xposition, motion_yposition, motion_direction,
        motion_scroll_right, motion_scroll_up, motion_align_scene, motion_xscroll, motion_yscroll,//have no purpose
        //Motion menus
        motion_goto_menu, motion_pointtowards_menu, motion_glideto_menu,
        //Operator primitives
        operator_add, operator_subtract, operator_multiply, operator_divide,
        operator_lt, operator_equals, operator_gt, operator_and, operator_or, operator_not,
        operator_random, operator_join, operator_letter_of, operator_length, operator_contains,
        operator_mod, operator_round, operator_mathop,
        //Procedures primitives
        procedures_definition, procedures_call,procedures_prototype, argument_reporter_string_number, argument_reporter_boolean,
        //Sensing primitives
        sensing_touchingobject, sensing_touchingcolor, sensing_coloristouchingcolor, sensing_distanceto,
        sensing_timer, sensing_resettimer, sensing_of, sensing_mousex, sensing_mousey, sensing_setdragmode,
        sensing_mousedown, sensing_keypressed, sensing_current, sensing_dayssince2000,
        sensing_loudness, sensing_loud, sensing_askandwait, sensing_answer, sensing_username, sensing_userid,
        //Sensing menus
        sensing_of_object_menu, sensing_distancetomenu , sensing_touchingobjectmenu , sensing_keyoptions,
        //Sound primitives
        sound_play, sound_playuntildone, sound_stopallsounds, sound_seteffectto, sound_changeeffectby,
        sound_cleareffects, sound_sounds_menu, sound_beats_menu, sound_effects_menu,
        sound_setvolumeto, sound_changevolumeby, sound_volume,
        //Pen primitives
        pen_clear,pen_stamp, pen_penDown, pen_penUp, pen_setPenColortoColor, pen_changePenColorParamBy,
        pen_setPenColorParamTo, pen_changePenSizeBy, pen_setPenSizeTo,
        //Pen menus
        pen_menu_colorParam,
        //Music primtives
        music_playDrumForBeats, music_restForBeats, music_playNoteForBeats, music_setInstrument,
        music_setTempo, music_getTempo, music_changeTempo,
        //Music menus
        music_menu_DRUM, note, music_menu_INSTRUMENT


    }

    public enum ScratchBlockType
    {
        Hat,Stack, Boolean , Reporter, C, Cap , Menu
    }


    internal partial class ScratchBlock
    {
        public static Dictionary<ScratchBlockOpCode, ScratchBlockType> BlockTypes = new Dictionary<ScratchBlockOpCode, ScratchBlockType>()
        {
            {ScratchBlockOpCode.control_repeat,ScratchBlockType.C},
            {ScratchBlockOpCode.control_repeat_until,ScratchBlockType.C},
            {ScratchBlockOpCode.control_while,ScratchBlockType.C},
            {ScratchBlockOpCode.control_for_each,ScratchBlockType.C},
            {ScratchBlockOpCode.control_forever,ScratchBlockType.C},
            {ScratchBlockOpCode.control_wait,ScratchBlockType.Stack},
            {ScratchBlockOpCode.control_wait_until,ScratchBlockType.Stack},
            {ScratchBlockOpCode.control_if,ScratchBlockType.C},
            {ScratchBlockOpCode.control_if_else,ScratchBlockType.C},
            {ScratchBlockOpCode.control_stop,ScratchBlockType.Stack},
            {ScratchBlockOpCode.control_create_clone_of,ScratchBlockType.Stack},
            {ScratchBlockOpCode.control_delete_this_clone,ScratchBlockType.Cap},
            {ScratchBlockOpCode.control_get_counter,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.control_incr_counter,ScratchBlockType.Stack},
            {ScratchBlockOpCode.control_clear_counter,ScratchBlockType.Stack},
            {ScratchBlockOpCode.control_all_at_once,ScratchBlockType.C},
            {ScratchBlockOpCode.control_start_as_clone,ScratchBlockType.Hat},
            {ScratchBlockOpCode.control_create_clone_of_menu,ScratchBlockType.Menu},
            {ScratchBlockOpCode.data_variable,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.data_setvariableto,ScratchBlockType.Stack},
            {ScratchBlockOpCode.data_changevariableby,ScratchBlockType.Stack},
            {ScratchBlockOpCode.data_hidevariable,ScratchBlockType.Stack},
            {ScratchBlockOpCode.data_showvariable,ScratchBlockType.Stack},
            {ScratchBlockOpCode.data_listcontents,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.data_addtolist,ScratchBlockType.Stack},
            {ScratchBlockOpCode.data_deleteoflist,ScratchBlockType.Stack},
            {ScratchBlockOpCode.data_deletealloflist,ScratchBlockType.Stack},
            {ScratchBlockOpCode.data_insertatlist,ScratchBlockType.Stack},
            {ScratchBlockOpCode.data_replaceitemoflist,ScratchBlockType.Stack},
            {ScratchBlockOpCode.data_itemoflist,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.data_itemnumoflist,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.data_lengthoflist,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.data_listcontainsitem,ScratchBlockType.Boolean},
            {ScratchBlockOpCode.data_hidelist,ScratchBlockType.Stack},
            {ScratchBlockOpCode.data_showlist,ScratchBlockType.Stack},
            {ScratchBlockOpCode.event_broadcast,ScratchBlockType.Stack},
            {ScratchBlockOpCode.event_broadcastandwait,ScratchBlockType.Stack},
            {ScratchBlockOpCode.event_whenflagclicked,ScratchBlockType.Hat},
            {ScratchBlockOpCode.event_whenkeypressed,ScratchBlockType.Hat},
            {ScratchBlockOpCode.event_whenthisspriteclicked,ScratchBlockType.Hat},
            {ScratchBlockOpCode.event_whentouchingobject,ScratchBlockType.Hat},
            {ScratchBlockOpCode.event_whenstageclicked,ScratchBlockType.Hat},
            {ScratchBlockOpCode.event_whenbackdropswitchesto,ScratchBlockType.Hat},
            {ScratchBlockOpCode.event_whengreaterthan,ScratchBlockType.Hat},
            {ScratchBlockOpCode.event_whenbroadcastreceived,ScratchBlockType.Hat},
            {ScratchBlockOpCode.looks_say,ScratchBlockType.Stack},
            {ScratchBlockOpCode.looks_sayforsecs,ScratchBlockType.Stack},
            {ScratchBlockOpCode.looks_think,ScratchBlockType.Stack},
            {ScratchBlockOpCode.looks_thinkforsecs,ScratchBlockType.Stack},
            {ScratchBlockOpCode.looks_show,ScratchBlockType.Stack},
            {ScratchBlockOpCode.looks_hide,ScratchBlockType.Stack},
            {ScratchBlockOpCode.looks_hideallsprites,ScratchBlockType.Stack},
            {ScratchBlockOpCode.looks_switchcostumeto,ScratchBlockType.Stack},
            {ScratchBlockOpCode.looks_switchbackdropto,ScratchBlockType.Stack},
            {ScratchBlockOpCode.looks_switchbackdroptoandwait,ScratchBlockType.Stack},
            {ScratchBlockOpCode.looks_nextcostume,ScratchBlockType.Stack},
            {ScratchBlockOpCode.looks_nextbackdrop,ScratchBlockType.Stack},
            {ScratchBlockOpCode.looks_changeeffectby,ScratchBlockType.Stack},
            {ScratchBlockOpCode.looks_seteffectto,ScratchBlockType.Stack},
            {ScratchBlockOpCode.looks_cleargraphiceffects,ScratchBlockType.Stack},
            {ScratchBlockOpCode.looks_changesizeby,ScratchBlockType.Stack},
            {ScratchBlockOpCode.looks_setsizeto,ScratchBlockType.Stack},
            {ScratchBlockOpCode.looks_changestretchby,ScratchBlockType.Stack},
            {ScratchBlockOpCode.looks_setstretchto,ScratchBlockType.Stack},
            {ScratchBlockOpCode.looks_gotofrontback,ScratchBlockType.Stack},
            {ScratchBlockOpCode.looks_goforwardbackwardlayers,ScratchBlockType.Stack},
            {ScratchBlockOpCode.looks_size,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.looks_costumenumbername,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.looks_backdropnumbername,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.looks_costume,ScratchBlockType.Menu },
            {ScratchBlockOpCode.looks_backdrops,ScratchBlockType.Menu },
            {ScratchBlockOpCode.motion_movesteps,ScratchBlockType.Stack},
            {ScratchBlockOpCode.motion_gotoxy,ScratchBlockType.Stack},
            {ScratchBlockOpCode.motion_goto,ScratchBlockType.Stack},
            {ScratchBlockOpCode.motion_turnright,ScratchBlockType.Stack},
            {ScratchBlockOpCode.motion_turnleft,ScratchBlockType.Stack},
            {ScratchBlockOpCode.motion_pointindirection,ScratchBlockType.Stack},
            {ScratchBlockOpCode.motion_pointtowards,ScratchBlockType.Stack},
            {ScratchBlockOpCode.motion_glidesecstoxy,ScratchBlockType.Stack},
            {ScratchBlockOpCode.motion_glideto,ScratchBlockType.Stack},
            {ScratchBlockOpCode.motion_ifonedgebounce,ScratchBlockType.Stack},
            {ScratchBlockOpCode.motion_setrotationstyle,ScratchBlockType.Stack},
            {ScratchBlockOpCode.motion_changexby,ScratchBlockType.Stack},
            {ScratchBlockOpCode.motion_setx,ScratchBlockType.Stack},
            {ScratchBlockOpCode.motion_changeyby,ScratchBlockType.Stack},
            {ScratchBlockOpCode.motion_sety,ScratchBlockType.Stack},
            {ScratchBlockOpCode.motion_xposition,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.motion_yposition,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.motion_direction,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.motion_scroll_right,ScratchBlockType.Stack},
            {ScratchBlockOpCode.motion_scroll_up,ScratchBlockType.Stack},
            {ScratchBlockOpCode.motion_align_scene,ScratchBlockType.Stack},
            {ScratchBlockOpCode.motion_xscroll,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.motion_yscroll,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.motion_goto_menu,ScratchBlockType.Menu},
            {ScratchBlockOpCode.motion_pointtowards_menu,ScratchBlockType.Menu},
            {ScratchBlockOpCode.motion_glideto_menu,ScratchBlockType.Menu},
            {ScratchBlockOpCode.operator_add,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.operator_subtract,ScratchBlockType.Reporter },
            {ScratchBlockOpCode.operator_multiply,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.operator_divide,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.operator_lt,ScratchBlockType.Boolean},
            {ScratchBlockOpCode.operator_equals,ScratchBlockType.Boolean},
            {ScratchBlockOpCode.operator_gt,ScratchBlockType.Boolean},
            {ScratchBlockOpCode.operator_and,ScratchBlockType.Boolean},
            {ScratchBlockOpCode.operator_or,ScratchBlockType.Boolean},
            {ScratchBlockOpCode.operator_not,ScratchBlockType.Boolean},
            {ScratchBlockOpCode.operator_random,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.operator_join,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.operator_letter_of,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.operator_length,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.operator_contains,ScratchBlockType.Boolean},
            {ScratchBlockOpCode.operator_mod,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.operator_round,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.operator_mathop,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.procedures_definition,ScratchBlockType.Hat},
            {ScratchBlockOpCode.procedures_call,ScratchBlockType.Stack},
            {ScratchBlockOpCode.procedures_prototype,ScratchBlockType.Menu},
            {ScratchBlockOpCode.argument_reporter_string_number,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.argument_reporter_boolean,ScratchBlockType.Boolean},
            {ScratchBlockOpCode.sensing_touchingobject,ScratchBlockType.Boolean},
            {ScratchBlockOpCode.sensing_touchingcolor,ScratchBlockType.Boolean},
            {ScratchBlockOpCode.sensing_coloristouchingcolor,ScratchBlockType.Boolean},
            {ScratchBlockOpCode.sensing_distanceto,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.sensing_timer,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.sensing_resettimer,ScratchBlockType.Stack},
            {ScratchBlockOpCode.sensing_of,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.sensing_mousex,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.sensing_mousey,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.sensing_setdragmode,ScratchBlockType.Stack},
            {ScratchBlockOpCode.sensing_mousedown,ScratchBlockType.Boolean},
            {ScratchBlockOpCode.sensing_keypressed,ScratchBlockType.Boolean},
            {ScratchBlockOpCode.sensing_current,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.sensing_dayssince2000,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.sensing_loudness,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.sensing_loud,ScratchBlockType.Boolean},
            {ScratchBlockOpCode.sensing_askandwait,ScratchBlockType.Stack},
            {ScratchBlockOpCode.sensing_answer,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.sensing_username,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.sensing_userid,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.sensing_of_object_menu,ScratchBlockType.Menu},
            {ScratchBlockOpCode.sensing_distancetomenu,ScratchBlockType.Menu},
            {ScratchBlockOpCode.sensing_touchingobjectmenu,ScratchBlockType.Menu},
            {ScratchBlockOpCode.sensing_keyoptions,ScratchBlockType.Menu},
            {ScratchBlockOpCode.sound_play,ScratchBlockType.Stack},
            {ScratchBlockOpCode.sound_playuntildone,ScratchBlockType.Stack},
            {ScratchBlockOpCode.sound_stopallsounds,ScratchBlockType.Stack},
            {ScratchBlockOpCode.sound_seteffectto,ScratchBlockType.Stack},
            {ScratchBlockOpCode.sound_changeeffectby,ScratchBlockType.Stack},
            {ScratchBlockOpCode.sound_cleareffects,ScratchBlockType.Stack},
            {ScratchBlockOpCode.sound_sounds_menu,ScratchBlockType.Menu},
            {ScratchBlockOpCode.sound_beats_menu,ScratchBlockType.Menu},
            {ScratchBlockOpCode.sound_effects_menu,ScratchBlockType.Menu},
            {ScratchBlockOpCode.sound_setvolumeto,ScratchBlockType.Stack},
            {ScratchBlockOpCode.sound_changevolumeby,ScratchBlockType.Stack},
            {ScratchBlockOpCode.sound_volume,ScratchBlockType.Reporter},
            //Pen
            {ScratchBlockOpCode.pen_clear,ScratchBlockType.Stack},
            {ScratchBlockOpCode.pen_stamp,ScratchBlockType.Stack},
            {ScratchBlockOpCode.pen_penDown,ScratchBlockType.Stack},
            {ScratchBlockOpCode.pen_penUp,ScratchBlockType.Stack},
            {ScratchBlockOpCode.pen_setPenColortoColor,ScratchBlockType.Stack},
            {ScratchBlockOpCode.pen_changePenColorParamBy,ScratchBlockType.Stack},
            {ScratchBlockOpCode.pen_setPenColorParamTo,ScratchBlockType.Stack},
            {ScratchBlockOpCode.pen_changePenSizeBy,ScratchBlockType.Stack},
            {ScratchBlockOpCode.pen_setPenSizeTo,ScratchBlockType.Stack},
            {ScratchBlockOpCode.pen_menu_colorParam,ScratchBlockType.Menu},
            //Music
            {ScratchBlockOpCode.music_playDrumForBeats,ScratchBlockType.Stack},
            {ScratchBlockOpCode.music_restForBeats,ScratchBlockType.Stack},
            {ScratchBlockOpCode.music_playNoteForBeats,ScratchBlockType.Stack},
            {ScratchBlockOpCode.music_setInstrument,ScratchBlockType.Stack},
            {ScratchBlockOpCode.music_setTempo,ScratchBlockType.Stack},
            {ScratchBlockOpCode.music_getTempo,ScratchBlockType.Reporter},
            {ScratchBlockOpCode.music_changeTempo,ScratchBlockType.Stack},
            {ScratchBlockOpCode.music_menu_DRUM,ScratchBlockType.Stack},
            {ScratchBlockOpCode.note,ScratchBlockType.Stack},
            {ScratchBlockOpCode.music_menu_INSTRUMENT,ScratchBlockType.Stack},
        };

    }
   
}
